import React, { useEffect, useState, useMemo } from "react";
import { Link, useParams, useNavigate } from "react-router-dom";
import { ArrowLeft, Play, Trash, Code, FlowArrow, Lightning } from "@phosphor-icons/react";
import { toast } from "sonner";
import api from "@/api/client";
import { StatusBadge } from "@/components/StatusBadge";
import PipelineDAG from "@/components/PipelineDAG";
import { formatDistanceToNow } from "date-fns";

export default function PipelineDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [p, setP] = useState(null);
  const [runs, setRuns] = useState([]);
  const [tab, setTab] = useState("overview");
  const [running, setRunning] = useState(false);

  const load = async () => {
    try {
      const [pr, rr] = await Promise.all([
        api.get(`/pipelines/${id}`),
        api.get(`/pipelines/${id}/runs`),
      ]);
      setP(pr.data);
      setRuns(rr.data);
    } catch {
      toast.error("Pipeline not found");
      navigate("/app/pipelines");
    }
  };

  useEffect(() => { load(); }, [id]);

  // poll if there's an active run
  useEffect(() => {
    const active = runs.some((r) => r.status === "running");
    if (!active) return;
    const t = setInterval(() => {
      api.get(`/pipelines/${id}/runs`).then(({ data }) => setRuns(data));
    }, 2000);
    return () => clearInterval(t);
  }, [runs, id]);

  const startRun = async () => {
    setRunning(true);
    try {
      const { data } = await api.post(`/pipelines/${id}/run`);
      toast.success("Run started");
      // navigate to run detail
      navigate(`/app/runs/${data.run_id}`);
    } catch (err) {
      toast.error(err?.response?.data?.detail || "Failed to start run");
    } finally {
      setRunning(false);
    }
  };

  const remove = async () => {
    if (!window.confirm("Delete this pipeline?")) return;
    await api.delete(`/pipelines/${id}`);
    toast.success("Deleted");
    navigate("/app/pipelines");
  };

  if (!p) return <div className="text-[#71717A] font-mono text-sm"><span className="ascii-loader" /> loading...</div>;

  return (
    <div className="space-y-6">
      <Link to="/app/pipelines" className="text-xs text-[#71717A] hover:text-white inline-flex items-center gap-1"><ArrowLeft size={12} /> back to pipelines</Link>

      <header className="flex items-start justify-between gap-4">
        <div className="min-w-0">
          <div className="flex items-center gap-3 flex-wrap">
            <div className="micro-label">// pipeline</div>
            <span className="badge">{p.target_platform}</span>
            <span className="badge badge-info">{p.cloud_target.toUpperCase()}</span>
            <span className="badge">{p.deploy_strategy}</span>
          </div>
          <h1 className="mt-2 font-display font-black text-3xl tracking-tighter truncate">{p.name}</h1>
          <div className="text-sm text-[#A1A1AA] mt-1 font-mono">{p.repo_name}</div>
        </div>
        <div className="flex items-center gap-2">
          <button data-testid="pipeline-run-btn" onClick={startRun} disabled={running} className="btn-primary inline-flex items-center gap-2">
            {running ? <span className="ascii-loader" /> : <><Play size={14} weight="fill" /> Run pipeline</>}
          </button>
          <button onClick={remove} data-testid="pipeline-delete-btn" className="btn-secondary inline-flex items-center gap-2 text-[#E54D2E] hover:bg-[#E54D2E]/10">
            <Trash size={14} />
          </button>
        </div>
      </header>

      {/* tabs */}
      <div className="border-b border-[#262626] flex gap-1">
        {[
          ["overview", "Overview"],
          ["yaml", "Pipeline YAML"],
          ["runs", `Runs (${runs.length})`],
        ].map(([k, l]) => (
          <button
            key={k}
            data-testid={`tab-${k}`}
            onClick={() => setTab(k)}
            className={`px-4 py-2.5 text-sm border-b-2 -mb-px transition-colors ${
              tab === k ? "border-[#E54D2E] text-white" : "border-transparent text-[#A1A1AA] hover:text-white"
            }`}
          >
            {l}
          </button>
        ))}
      </div>

      {tab === "overview" && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
          <div className="lg:col-span-2 surface p-6">
            <div className="micro-label mb-4">// pipeline graph</div>
            <PipelineDAG stages={p.stages || []} run={null} />
          </div>
          <div className="surface p-6 space-y-4">
            <div>
              <div className="micro-label">// generated by</div>
              <div className="font-mono text-sm mt-1 flex items-center gap-2"><Lightning size={12} color="#E54D2E" weight="fill" /> {p.model}</div>
            </div>
            <div>
              <div className="micro-label">// created</div>
              <div className="text-sm mt-1">{formatDistanceToNow(new Date(p.created_at), { addSuffix: true })}</div>
            </div>
            <div>
              <div className="micro-label">// stages</div>
              <div className="text-sm mt-1 font-mono text-[#A1A1AA]">{(p.stages || []).join(" → ")}</div>
            </div>
            <div>
              <div className="micro-label">// total runs</div>
              <div className="font-mono text-3xl mt-1">{p.run_count}</div>
            </div>
          </div>
        </div>
      )}

      {tab === "yaml" && (
        <div className="surface-panel overflow-hidden">
          <div className="px-4 py-2.5 border-b border-[#262626] bg-[#0a0a0a] flex items-center justify-between">
            <span className="font-mono text-xs text-[#A1A1AA]"><Code size={12} className="inline mr-1" weight="duotone" color="#E54D2E" /> {pipelineFile(p.target_platform)}</span>
            <button onClick={() => { navigator.clipboard.writeText(p.yaml_content); toast.success("Copied"); }} className="btn-ghost text-xs" data-testid="copy-yaml-btn">copy</button>
          </div>
          <pre className="p-5 font-mono text-xs leading-relaxed text-[#EDEDED] bg-black whitespace-pre-wrap max-h-[600px] overflow-auto" data-testid="pipeline-yaml">
            {p.yaml_content}
          </pre>
        </div>
      )}

      {tab === "runs" && (
        <div className="surface overflow-hidden">
          {runs.length === 0 ? (
            <div className="p-16 text-center">
              <FlowArrow size={40} className="mx-auto text-[#262626]" />
              <div className="mt-4 font-display font-bold text-xl">No runs yet</div>
              <div className="text-sm text-[#A1A1AA] mt-2">Trigger your first run to see live logs.</div>
              <button onClick={startRun} className="btn-primary mt-6">Run pipeline now</button>
            </div>
          ) : (
            <table className="w-full text-sm">
              <thead className="bg-[#0a0a0a]">
                <tr className="text-left border-b border-[#262626]">
                  <th className="micro-label p-4">run id</th>
                  <th className="micro-label p-4">status</th>
                  <th className="micro-label p-4">commit</th>
                  <th className="micro-label p-4">stage</th>
                  <th className="micro-label p-4">started</th>
                </tr>
              </thead>
              <tbody>
                {runs.map((r) => (
                  <tr key={r.id} className="border-b border-[#1A1A1A] hover:bg-[#121212]">
                    <td className="p-4 font-mono text-xs"><Link to={`/app/runs/${r.id}`} data-testid={`run-row-${r.id}`} className="hover:text-[#E54D2E]">{r.id}</Link></td>
                    <td className="p-4"><StatusBadge status={r.status} /></td>
                    <td className="p-4 font-mono text-xs">{r.commit_sha || "—"}</td>
                    <td className="p-4 font-mono text-xs text-[#A1A1AA]">{r.failed_stage || r.current_stage || "—"}</td>
                    <td className="p-4 text-xs text-[#71717A]">{formatDistanceToNow(new Date(r.started_at), { addSuffix: true })}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      )}
    </div>
  );
}

function pipelineFile(platform) {
  return {
    "github-actions": ".github/workflows/ci.yml",
    "gitlab-ci": ".gitlab-ci.yml",
    "jenkins": "Jenkinsfile",
    "bitbucket": "bitbucket-pipelines.yml",
  }[platform] || "pipeline.yml";
}
